#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'apt'
cookbook 'ssh'
cookbook 'build-essential'
cookbook 'ark'
cookbook 'ruby_build',
  :git => "https://github.com/mojolingo/chef-ruby_build",
  :ref => "ruby-2.1.0"
cookbook 'chruby'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
